[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = []

[start]
cmd = 'cd backend && node index.js'

[phases.cleanup]
cmds = ['rm -rf /nix/var/nix/gcroots/auto/*']
dependsOn = ['build']