[build]
builder = "nixpacks"
buildCommand = "npm ci"

[deploy]
startCommand = "node --max-old-space-size=512 index.js"
healthcheckPath = "/health"
healthcheckTimeout = 5

[deploy.env]
NODE_ENV = "production"